version: "3.9"

services:
  mysql:
    image: mysql
    container_name: duomenu-bazeliumbas
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: verygoodpassword
      MYSQL_DATABASE: eshopdb
      MYSQL_USER: eshop_user
      MYSQL_PASSWORD: eshop_password
    ports:
      - "3307:3306"
#    postgresql:
#      image: postgres
#      container_name: duomenu-bazeliumbas
#      command: x
#      restart: always
#      environment:
#        MYSQL_ROOT_PASSWORD: verygoodpassword
#        MYSQL_DATABASE: eshopdb
#        MYSQL_USER: eshop_user
#        MYSQL_PASSWORD: eshop_password
#      ports:
#        - "3307:3306"

#    rabbitmq:
#      image: rabbitmq
      #config below
